"use client";

import { useState, useEffect } from "react";
import { useSearchParams } from "next/navigation";

interface Question {
  question: string;
  options: string[];
  correctAnswer: number;
}

export default function QuizPage() {
  const searchParams = useSearchParams();
  const [questions, setQuestions] = useState<Question[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const numberOfQuestions = searchParams.get("questions");
  const subject = searchParams.get("subject") || "general knowledge";

  useEffect(() => {
    if (numberOfQuestions) {
      generateQuiz();
    }
  }, [numberOfQuestions]);

  const generateQuiz = async () => {
    try {
      setLoading(true);
      setError(null);

      const response = await fetch("/api/generate-quiz", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          numberOfQuestions: parseInt(numberOfQuestions!),
          subject: subject,
        }),
      });

      const data = await response.json();

      if (data.success) {
        setQuestions(data.questions);
      } else {
        setError(data.error || "Failed to generate quiz");
        setQuestions(data.questions || []); // Use fallback questions
      }
    } catch (error) {
      setError("Failed to connect to the quiz generation service");
      console.error("Error:", error);
    } finally {
      setLoading(false);
    }
  };

  if (loading) {
    return (
      <div className="p-8 flex flex-col items-center justify-center min-h-screen">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto mb-4"></div>
          <h1 className="text-2xl font-bold text-gray-800 mb-2">
            Generating Quiz...
          </h1>
          <p className="text-gray-600">
            Creating {numberOfQuestions} questions about {subject}
          </p>
        </div>
      </div>
    );
  }

  if (error && questions.length === 0) {
    return (
      <div className="p-8 flex flex-col items-center justify-center min-h-screen">
        <div className="text-center max-w-md">
          <h1 className="text-2xl font-bold text-red-600 mb-4">Error</h1>
          <p className="text-gray-700 mb-4">{error}</p>
          <button
            onClick={generateQuiz}
            className="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
          >
            Try Again
          </button>
        </div>
      </div>
    );
  }

  if (questions.length === 0) {
    return (
      <div className="p-8 flex flex-col items-center justify-center min-h-screen">
        <div className="text-center">
          <h1 className="text-2xl font-bold text-gray-800 mb-4">
            No Questions Generated
          </h1>
          <p className="text-gray-600 mb-4">Please go back and try again.</p>
          <button
            onClick={() => (window.location.href = "/test")}
            className="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
          >
            Back to Test Setup
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="p-8 max-w-4xl mx-auto">
      {error && (
        <div className="mb-4 p-4 bg-yellow-100 border border-yellow-400 rounded-lg">
          <p className="text-yellow-800">
            ⚠️ {error} (Using fallback questions)
          </p>
        </div>
      )}

      <div className="mb-8">
        <h1 className="text-3xl font-bold text-gray-800 mb-2">
          Generated Quiz: {subject}
        </h1>
        <p className="text-gray-600">
          {questions.length} questions generated by AI
        </p>
      </div>

      <div className="space-y-6">
        {questions.map((question, questionIndex) => (
          <div
            key={questionIndex}
            className="bg-white p-6 rounded-lg shadow-sm border border-gray-100"
          >
            <h2 className="text-xl font-medium mb-4 text-gray-800">
              Question {questionIndex + 1}: {question.question}
            </h2>

            <div className="space-y-3">
              {question.options.map((option, optionIndex) => (
                <div
                  key={optionIndex}
                  className={`p-4 rounded-lg border-2 ${
                    optionIndex === question.correctAnswer
                      ? "border-green-500 bg-green-50"
                      : "border-gray-200 bg-gray-50"
                  }`}
                >
                  <div className="flex items-center justify-between">
                    <span className="text-gray-700">
                      <span className="font-medium text-gray-600 mr-3">
                        {String.fromCharCode(65 + optionIndex)}.
                      </span>
                      {option}
                    </span>
                    {optionIndex === question.correctAnswer && (
                      <span className="text-green-600 font-medium text-sm">
                        ✓ Correct Answer
                      </span>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </div>
        ))}
      </div>

      <div className="mt-8 flex justify-center">
        <button
          onClick={() => (window.location.href = "/test")}
          className="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
        >
          Generate New Quiz
        </button>
      </div>
    </div>
  );
}
